# Guest-side host RPC bridge (loaded by main.rb before user code).
#
# User code calls SB.call(name, args) and it behaves like a regular,
# blocking Ruby function: the request is written to /work/rpc_req.json,
# the wasm import (SBExt.call — the sb_rpc gem statically linked into
# the image) is invoked, and the guest blocks while the host executes
# the registered handler. The response is read back from
# /work/rpc_resp.json.
#
# Handler failures never cross the wasm boundary: the host encodes them
# as {"ok": false, "error": {"class", "message"}} responses, surfaced
# here as SB::ToolError (SB::UnknownTool for unregistered names) so user
# code can rescue them.
module SB
  # Raised when an RPC handler fails or its result is unusable.
  class ToolError < StandardError; end

  # Raised when the code calls a name the host did not register —
  # including when the sandbox has no handlers configured at all.
  class UnknownTool < ToolError; end

  # Raised when the transport itself fails (image without the guest
  # gems, broken /work channel).
  class RpcUnavailable < StandardError; end

  begin
    # /bundle/setup.rb is generated by the image build; it adds the gem
    # lib dirs to $LOAD_PATH. The gems are absent when the image was
    # built without the guest_ext bundle; SB.call then reports it
    # cleanly instead of crashing on NameError.
    require "/bundle/setup.rb"
    require "sb_rpc"
  rescue LoadError
    nil
  end

  module_function

  # Calls a host-registered handler and returns its result. Behaves as a
  # blocking function call; the LLM-facing contract is plain Ruby.
  #
  #   SB.call("github.search", q: "x")          # kwargs form
  #   SB.call("github.search", { "q" => "x" })  # positional hash form
  #
  # `name` and `args` must be JSON-serializable; handlers receive the
  # JSON-parsed args (string keys) and return a JSON-serializable value.
  def call(name, args = nil, **kwargs)
    unless name.is_a?(String) && !name.empty?
      raise ArgumentError, "rpc name must be a non-empty String, got #{name.inspect}"
    end
    unless defined?(SBExt)
      raise RpcUnavailable, "rpc support is not available in this image (sb_rpc gem missing)"
    end

    merged = args.nil? ? {} : args
    merged = merged.merge(kwargs) unless kwargs.empty?
    request = begin
      JSON.generate({ name: name, args: merged })
    rescue StandardError, TypeError => e
      raise TypeError, "rpc arguments must be JSON-serializable: #{e.message}"
    end

    File.write(File.join(WORK_DIR, "rpc_req.json"), request)
    status = SBExt.call
    unless status.zero?
      raise RpcUnavailable, "rpc transport failed (status #{status})"
    end

    response = JSON.parse(File.read(File.join(WORK_DIR, "rpc_resp.json")))
    unless response["ok"]
      error = response["error"] || {}
      klass = error["class"] == "SB::UnknownTool" ? UnknownTool : ToolError
      raise klass, error["message"].to_s
    end
    response["result"]
  end
end
